### ISSUE TITLE
How do I regenerate the parser?

### ISSUE THREAD

**Issue by Ki11erRabbit** [RustPython/Parser#113]
I am using this library for a research project that requires me to modify the grammar of Python. I have been stuck trying to regenerate the parser since I am not sure what is means to "Run `lalrpop src/python.lalrpop`."

Any help is appreciated.
Thank you.

**Comment by youknowone** [comment]
The source file is here: https://github.com/RustPython/Parser/blob/main/parser/src/python.lalrpop
You can install lalrpop the compiler from cargo.

**Comment by Ki11erRabbit** [comment]
Thank
