### ISSUE TITLE
Implement `ToString` for `Identifier` and `Constant`

### ISSUE THREAD

**Issue by MichaReiser** [RustPython/Parser#28]
Would it be useful to implement `ToString` for `Identifier` and `Constant`?

**Comment by youknowone** [comment]
ToString for Constant is looking very useful.

I wish Identifier can call it through `Deref<Target=str>`, but adding one will be good too for optimization.
(In the long term, I wish I can remove String from them through #21.)

**Comment by MichaReiser** [comment]
Good point, this should work already out of the box, thanks to `Deref<str>
