### ISSUE TITLE
PEP 695 – Type Parameter Syntax

### ISSUE THREAD

**Issue by tjf801** [RustPython/Parser#82]
## Feature

Seeing as how Python 3.12 is now in beta, I feel like RustPython should also work on being able to parse the new syntax introduced in [PEP 695](https://peps.python.org/pep-0695/), which makes it much easier to type-hint generic functions and types in the language. I ran into this while trying to start writing a custom type checker, and wanted to use `rustpython_ast` to parse Python 3.12 code that uses this new syntax. Some examples include:
```python
def identity[T](x: T) -> T:
    return x

type Point = tuple[float, float]

type MappingOrSequence[T] = Mapping[int, T] | Sequence[T]

class Container[T](Sequence[T]): ...
```

## Python Documentation or reference to CPython source code

 - [The `type` statement](https://docs.python.org/3.12/reference/simple_stmts.html#type)
 - [Generic functions](https://docs.python.org/3.12/reference/compound_stmts.html#generic-functions)
 - [Generic classes](https://docs.python.org/3.12/reference/compound_stmts.html#generic-classes)
 - [Generic type aliases](https://docs.python.org/3.12/reference/compound_stmts.html#generic-type-aliases)

**Comment by zanieb** [comment]
I'll be working on this for use in Ruff — I expect my changes will land in a pull request here.
